name: LEM LATTIMER
favicon: null
layout_spectrum: 0.453995400108397
typography_spectrum: 0.07914879103191197
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fff1d9'
    - '#b2bfc4'
    - '#003d56'
    - '#4a86a0'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.7561225946992636
  saturation: 0.6659694546833634
  rhythmicContrast: 0.1990460257511586
purpose: []
